
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 550803
	#The name of the modpack
	modpackName = "Valhelsia 5"
	#The version of the modpack
	modpackVersion = "5.0.18"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

